### PR TITLE
Update installation.md

### PR DESCRIPTION
**Pull request by kkrieger85**
Specify laravel/framework dependency

### CODE REVIEW

**Review by fulopattila122 — CHANGES_REQUESTED** [review]
It makes sense to mention it here, but Vanilo works with Laravel versions 5.4 - 5.8

**Comment by kkrieger85** [comment]
Therefore I made this PR to Vanilo 0.5 docs - not to master. 

BTW: I just tried to install vanilo 0.5 with laravel 5.8 and it did not work out of the box

**Review by kkrieger85 — COMMENTED** [review]
OK

**Comment by fulopattila122** [comment]
Compatibility issue has been solved, see artkonekt/menu#3; Vanilo 0.5 now works with Laravel 5.8 as well.

Thanks for the notice :+1:

**Pull request closed without merging**
